apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: database-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/rinnguyen-groove/argocd-demo.git
    targetRevision: HEAD
    path: demo3/workloads/database

  destination:
    server: https://kubernetes.default.svc
    namespace: database

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
